### ISSUE TITLE
No properties, no fluidsynth showing

### ISSUE THREAD

**Issue by kostasxyz** [swami/swami#32] opened 2020-04-09 09:49 UTC
Installed on Ubuntu 20.04 and properties window is empty. Also Fluidsynth is lot loading.

![image](https://user-images.githubusercontent.com/1220837/78882337-985e7e00-7a60-11ea-8c20-e6c781d07a23.png)

**Comment by derselbst** [comment] 2020-04-09 09:58
Which version of swami are you running?
Which version of fluidsynth?
Pls. start swami from console and provide the console log.

**Comment by kostasxyz** [comment] 2020-04-09 10:04
I am running Swami 2.2.0
FluidSynth executable version 2.1.1


```Gtk-Message: 13:03:28.861: Failed to load module "canberra-gtk-module"

(swami:8534): libswamigui-CRITICAL **: 13:03:28.917: Failed to load UI XML file 'share/swami/swami-2.ui': Failed to open file “share/swami/swami-2.ui”: No such file or directory

(swami:8534): libswamigui-CRITICAL **: 13:03:28.917: Failed to load UI interface 'SwamiguiSplits': Failed to open file “share/swami/swami-2.ui”: No such file or directory

(swami:8534): Gtk-CRITICAL **: 13:03:28.917: gtk_box_pack: assertion 'GTK_IS_WIDGET (child)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.917: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.917: libglade widget not found: BtnNotes

(swami:8534): Gtk-CRITICAL **: 13:03:28.917: IA__gtk_toggle_button_set_active: assertion 'GTK_IS_TOGGLE_BUTTON (toggle_button)' failed

(swami:8534): GLib-GObject-WARNING **: 13:03:28.917: invalid (NULL) pointer instance

(swami:8534): GLib-GObject-CRITICAL **: 13:03:28.917: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.917: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.917: libglade widget not found: BtnNotesImage

(swami:8534): Gtk-CRITICAL **: 13:03:28.917: IA__gtk_image_set_from_stock: assertion 'GTK_IS_IMAGE (image)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.917: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.917: libglade widget not found: BtnVelocity

(swami:8534): GLib-GObject-WARNING **: 13:03:28.917: invalid (NULL) pointer instance

(swami:8534): GLib-GObject-CRITICAL **: 13:03:28.917: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.917: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.917: libglade widget not found: BtnVelocityImage

(swami:8534): Gtk-CRITICAL **: 13:03:28.917: IA__gtk_image_set_from_stock: assertion 'GTK_IS_IMAGE (image)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.917: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.917: libglade widget not found: SplitsVScrollBar

(swami:8534): Gtk-CRITICAL **: 13:03:28.917: IA__gtk_range_get_adjustment: assertion 'GTK_IS_RANGE (range)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.917: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.917: libglade widget not found: SplitsHScrollBar

(swami:8534): Gtk-CRITICAL **: 13:03:28.917: IA__gtk_range_get_adjustment: assertion 'GTK_IS_RANGE (range)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.917: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.917: libglade widget not found: SplitsScrollWinUpper

(swami:8534): Gtk-CRITICAL **: 13:03:28.917: IA__gtk_scrolled_window_set_hadjustment: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed

(swami:8534): Gtk-CRITICAL **: 13:03:28.917: IA__gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.918: libglade widget not found: SplitsScrollWinLower

(swami:8534): Gtk-CRITICAL **: 13:03:28.918: IA__gtk_scrolled_window_set_hadjustment: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed

(swami:8534): Gtk-CRITICAL **: 13:03:28.918: IA__gtk_scrolled_window_set_vadjustment: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed

(swami:8534): Gtk-CRITICAL **: 13:03:28.918: IA__gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.918: libglade widget not found: SpinBtnLowerOctave

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_control_prop_connect_widget: assertion 'G_IS_OBJECT (widget)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.918: libglade widget not found: ChkBtnJoinOctaves

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_control_prop_connect_widget: assertion 'G_IS_OBJECT (widget)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.918: libglade widget not found: SpinBtnUpperOctave

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_control_prop_connect_widget: assertion 'G_IS_OBJECT (widget)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.918: libglade widget not found: SpinBtnLowerVelocity

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_control_prop_connect_widget: assertion 'G_IS_OBJECT (widget)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.918: libglade widget not found: ChkBtnSameVelocity

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_control_prop_connect_widget: assertion 'G_IS_OBJECT (widget)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.918: libglade widget not found: SpinBtnUpperVelocity

(swami:8534): libswamigui-CRITICAL **: 13:03:28.918: swamigui_control_prop_connect_widget: assertion 'G_IS_OBJECT (widget)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.946: Failed to load UI interface 'Tips': Failed to open file “share/swami/swami-2.ui”: No such file or directory

(swami:8534): Gtk-CRITICAL **: 13:03:28.946: IA__gtk_window_set_transient_for: assertion 'GTK_IS_WINDOW (window)' failed

(swami:8534): Gtk-CRITICAL **: 13:03:28.946: IA__gtk_signal_connect_full: assertion 'GTK_IS_OBJECT (object)' failed

(swami:8534): GLib-GObject-CRITICAL **: 13:03:28.946: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.946: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.946: libglade widget not found: CHKagain

(swami:8534): Gtk-CRITICAL **: 13:03:28.946: IA__gtk_toggle_button_set_active: assertion 'GTK_IS_TOGGLE_BUTTON (toggle_button)' failed

(swami:8534): GLib-GObject-WARNING **: 13:03:28.946: invalid (NULL) pointer instance

(swami:8534): GLib-GObject-CRITICAL **: 13:03:28.946: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.946: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.946: libglade widget not found: BTNnext

(swami:8534): GLib-GObject-WARNING **: 13:03:28.946: invalid (NULL) pointer instance

(swami:8534): GLib-GObject-CRITICAL **: 13:03:28.946: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.946: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.946: libglade widget not found: BTNprev

(swami:8534): GLib-GObject-WARNING **: 13:03:28.946: invalid (NULL) pointer instance

(swami:8534): GLib-GObject-CRITICAL **: 13:03:28.946: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.946: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.946: libglade widget not found: BTNclose

(swami:8534): GLib-GObject-WARNING **: 13:03:28.946: invalid (NULL) pointer instance

(swami:8534): GLib-GObject-CRITICAL **: 13:03:28.946: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.946: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.946: libglade widget not found: BTNprev

(swami:8534): Gtk-CRITICAL **: 13:03:28.946: IA__gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.946: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.946: libglade widget not found: BTNnext

(swami:8534): Gtk-CRITICAL **: 13:03:28.946: IA__gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-CRITICAL **: 13:03:28.946: swamigui_util_glade_lookup_nowarn: assertion 'GTK_IS_WIDGET (widget)' failed

(swami:8534): libswamigui-WARNING **: 13:03:28.946: libglade widget not found: TXTview

(swami:8534): Gtk-CRITICAL **: 13:03:28.946: IA__gtk_text_view_get_buffer: assertion 'GTK_IS_TEXT_VIEW (text_view)' failed

(swami:8534): Gtk-CRITICAL **: 13:03:28.946: IA__gtk_text_buffer_set_text: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed

(swami:8534): GLib-GObject-CRITICAL **: 13:03:28.946: g_object_get_data: assertion 'G_IS_OBJECT (object)' failed

(swami:8534): Gtk-CRITICAL **: 13:03:28.946: IA__gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by derselbst** [comment] 2020-04-09 10:28
Ok, I see. Thanks.

The problem is that Ubuntu hasn't specified `CMAKE_INSTALL_DATADIR` when building swami. Usually, distributions have a macro that populates all the GNUInstallDirs correctly. I'll add an additional check to our build system and error out if `CMAKE_INSTALL_DATADIR` is not given.

**Comment by kostasxyz** [comment] 2020-04-09 10:38
@derselbst Many thanks!

**Comment by derselbst** [comment] 2020-04-09 13:43
Just found that when `CMAKE_INSTALL_DATADIR` is not set it defaults to a relative path. I've committed an appropriate fix. After that, I could not reproduce the issue anymore locally.

Thanks for the report. Feel free to test. I'll release Swami 2.2.1 within the next few days probably.

**Closed as completed** 2020-04-14 15:14 UTC
