### ISSUE TITLE
clicking on preferences crashes the application

### ISSUE THREAD

**Issue by mfs12** [swami/swami#61] opened 2021-01-18 09:04 UTC
Hey,

when i click on preferences the application crashes. i used 2.2.0 and 2.2.1. For building the PKGBUILD from Arch User Repository.

https://aur.archlinux.org/packages/swami/

Do you experience the same issue?

**Comment by mfs12** [comment] 2021-01-18 16:48
In function fluid_synth_pref_handler options pointer is not initialized, which means that it can point just somewhere and then used although no property with names "audio.driver-options" and "midi.driver-options" exist. Accessing this pointer then leads to segfault.

Initializing it with NULL, and checking if it changed when using helped in my case. But then the driver options for audio and midi stay empty in the preferences dialog.

**Comment by derselbst** [comment] 2021-01-19 17:10
Thanks for the report. Could you please share your preferences file? You find it in `$HOME/.config/swami/preferences.xml` .

@jjceresa Could you please have a look into this?

**Comment by mfs12** [comment] 2021-01-19 17:17
Sure... here is my config file.
```xml
<swami version="2.2.1">
  <prop name="patch-search-path"></prop>
  <prop name="patch-path"></prop>
  <prop name="sample-path"></prop>
  <prop name="sample-format"></prop>
  <prop name="swap-max-waste">64</prop>
  <prop name="swap-ram-size">32</prop>
  <prop name="sample-cache-max-waste">64</prop>
  <prop name="sample-cache-max-age">0</prop>
  <prop name="sample-max-size">32</prop>
  <prop name="update-interval">40</prop>
  <prop name="quit-confirm">1</prop>
  <prop name="splash-enable">1</prop>
  <prop name="splash-delay">5000</prop>
  <prop name="tips-enable">1</prop>
  <prop name="tips-position">7</prop>
  <prop name="piano-lower-keys">z,s,x,d,c,v,g,b,h,n,j,m,comma,l,period,semicolon,slash</prop>
  <prop name="piano-upper-keys">q,2,w,3,e,r,5,t,6,y,7,u,i,9,o,0,p,bracketleft,equal,bracketright</prop>
  <prop name="default-patch-type">IpatchSF2</prop>
  <prop name="middle-emul-enable">1</prop>
  <prop name="middle-emul-mod">0</prop>
  <plugin name="FluidSynth">
    <prop name="active-bank">127</prop>
    <prop name="active-program">127</prop>
    <prop name="interp">0</prop>
    <prop name="reverb-preset"></prop>
    <prop name="reverb-room-size">0.200000</prop>
    <prop name="reverb-damp">0.000000</prop>
    <prop name="reverb-width">0.500000</prop>
    <prop name="reverb-level">0.900000</prop>
    <prop name="chorus-preset"></prop>
    <prop name="chorus-count">3</prop>
    <prop name="chorus-level">2.000000</prop>
    <prop name="chorus-freq">0.300000</prop>
    <prop name="chorus-depth">8.000000</prop>
    <prop name="chorus-waveform">0</prop>
  </plugin>
</swami>
```
`

**Comment by jjceresa** [comment] 2021-01-19 19:05
@blnagain, Hello, your `preferences.xml` is strangely incomplete. Please could you do the following test.
- delete the file preferences.xml.
- start swami, then quit swami. When quitting swami the preferences.xml file is rebuild. You should get a file with 4349 bytes size.

Please, what fluidsynth version are you using during your issue ?
For information here using fluidsynth 2.1.2, my preference.xml is the following: 

```xml
<swami version="2.2.1">
  <prop name="patch-search-path"></prop>
  <prop name="patch-path">D:\Musiques\SoundFont\Piano_Rhodes_73.sf2</prop>
  <prop name="sample-path"></prop>
  <prop name="sample-format"></prop>
  <prop name="swap-max-waste">64</prop>
  <prop name="swap-ram-size">32</prop>
  <prop name="sample-cache-max-waste">64</prop>
  <prop name="sample-cache-max-age">0</prop>
  <prop name="sample-max-size">32</prop>
  <prop name="update-interval">40</prop>
  <prop name="quit-confirm">0</prop>
  <prop name="splash-enable">0</prop>
  <prop name="splash-delay">5000</prop>
  <prop name="tips-enable">0</prop>
  <prop name="tips-position">10</prop>
  <prop name="piano-lower-keys">z,s,x,d,c,v,g,b,h,n,j,m,comma,l,period,semicolon,slash</prop>
  <prop name="piano-upper-keys">q,2,w,3,e,r,5,t,6,y,7,u,i,9,o,0,p,bracketleft,equal,bracketright</prop>
  <prop name="default-patch-type">IpatchSF2</prop>
  <prop name="middle-emul-enable">1</prop>
  <prop name="middle-emul-mod">0</prop>
  <plugin name="FluidSynth">
    <prop name="active-bank">127</prop>
    <prop name="active-program">127</prop>
    <prop name="interp">0</prop>
    <prop name="reverb-preset"></prop>
    <prop name="reverb-room-size">1,000000</prop>
    <prop name="reverb-damp">0,000000</prop>
    <prop name="reverb-width">78,857143</prop>
    <prop name="reverb-level">0,034286</prop>
    <prop name="chorus-preset"></prop>
    <prop name="chorus-count">12</prop>
    <prop name="chorus-level">0,000000</prop>
    <prop name="chorus-freq">0,622285</prop>
    <prop name="chorus-depth">4,971428</prop>
    <prop name="chorus-waveform">0</prop>
    <prop name="audio-driver">dsound</prop>
    <prop name="audio-dsound-device">default</prop>
    <prop name="audio-file-endian">auto</prop>
    <prop name="audio-file-format">s16</prop>
    <prop name="audio-file-name">fluidsynth.wav</prop>
    <prop name="audio-file-type">auto</prop>
    <prop name="audio-period-size">512</prop>
    <prop name="audio-periods">8</prop>
    <prop name="audio-realtime-prio">60</prop>
    <prop name="audio-sample-format">16bits</prop>
    <prop name="audio-waveout-device">default</prop>
    <prop name="midi-autoconnect">0</prop>
    <prop name="midi-driver">winmidi</prop>
    <prop name="midi-portname"></prop>
    <prop name="midi-realtime-prio">50</prop>
    <prop name="midi-winmidi-device">default</prop>
    <prop name="player-reset-synth">1</prop>
    <prop name="player-timing-source">sample</prop>
    <prop name="shell-port">9800</prop>
    <prop name="shell-prompt"></prop>
    <prop name="synth-audio-channels">1</prop>
    <prop name="synth-audio-groups">1</prop>
    <prop name="synth-chorus-active">1</prop>
    <prop name="synth-chorus-depth">8,000000</prop>
    <prop name="synth-chorus-level">2,000000</prop>
    <prop name="synth-chorus-nr">3</prop>
    <prop name="synth-chorus-speed">0,300000</prop>
    <prop name="synth-cpu-cores">1</prop>
    <prop name="synth-default-soundfont">C:\soundfonts\default.sf2</prop>
    <prop name="synth-device-id">0</prop>
    <prop name="synth-dynamic-sample-loading">0</prop>
    <prop name="synth-effects-channels">2</prop>
    <prop name="synth-effects-groups">1</prop>
    <prop name="synth-gain">3,314285</prop>
    <prop name="synth-ladspa-active">0</prop>
    <prop name="synth-lock-memory">1</prop>
    <prop name="synth-midi-bank-select">gs</prop>
    <prop name="synth-midi-channels">16</prop>
    <prop name="synth-min-note-length">10</prop>
    <prop name="synth-overflow-age">1000,000000</prop>
    <prop name="synth-overflow-important">5000,000000</prop>
    <prop name="synth-overflow-important-channels"></prop>
    <prop name="synth-overflow-percussion">4000,000000</prop>
    <prop name="synth-overflow-released">-2000,000000</prop>
    <prop name="synth-overflow-sustained">-1000,000000</prop>
    <prop name="synth-overflow-volume">500,000000</prop>
    <prop name="synth-polyphony">256</prop>
    <prop name="synth-reverb-active">1</prop>
    <prop name="synth-reverb-damp">0,000000</prop>
    <prop name="synth-reverb-level">0,900000</prop>
    <prop name="synth-reverb-room-size">0,200000</prop>
    <prop name="synth-reverb-width">0,500000</prop>
    <prop name="synth-sample-rate">44100,000000</prop>
    <prop name="synth-threadsafe-api">1</prop>
    <prop name="synth-verbose">0</prop>
  </plugin>
</swami>
```

**Comment by jjceresa** [comment] 2021-01-19 19:18
Sorry, but github is really messy and doesn't work well with my browser. What you see in previous comment is the result when attaching my local preferences.xml file. the file is 4349 bytes.

@derselbst, please could you upload your preferences.xml file.

**Comment by mfs12** [comment] 2021-01-19 19:43
my fluidsynth version is 2.1.6

what i did:

- delete ~/.config/swami/preferences.xml
- started swami
- clicked edit->preferences
- crash
- ~/.config/swami/preferences.xml was not created

apparently it was only created with my patched version. This also explains why my perferences.xml is incomplete.

As i wrote there's something wrong in function fluid_synth_pref_handler, it tries to access some g_object_properties which does not exist. Don't you have any problems when your preferences.xml is gone?

**Comment by jjceresa** [comment] 2021-01-19 19:45
I forgot to say, here I am using swami 2.2.1 (not 2.2.0).

**Comment by mfs12** [comment] 2021-01-19 19:48
i am having this issue with both version of swami. i checked 2.2.0 and 2.2.1.

**Comment by jjceresa** [comment] 2021-01-19 19:55
>Don't you have any problems when your preferences.xml is gone?

No.

When swami crashes the preferences file cannot be written.

>As i wrote there's something wrong in function fluid_synth_pref_handler

The thing that is wrong, that the function should be more robust in case of missing property.
Please try recent fluidsynth version  and tell us what happens.

**Comment by mfs12** [comment] 2021-01-19 19:59
> Please try recent fluidsynth version and tell us what happens.

well, i am using the most recent version of fluidsynth, which is 2.1.6.

**Comment by mfs12** [comment] 2021-01-19 20:05
i mean i was using swami succesfully until i pressed the preferences button. And to me the bug is pretty clear. Although not sure it behaves everywhere the same, as Linux does not initialize all memory with '0's in release builds which explains why it's crashing. not sure how windows handles that.

**Comment by jjceresa** [comment] 2021-01-19 20:07
Please try this

-delete the file preferences.xml.
-start swami, then quit swami (without opening preferences dialog). When quitting swami the preferences.xml file is rebuild. What is the size of the file ?

**Comment by mfs12** [comment] 2021-01-19 20:11
I did as you told me to, my version of preferences.xml is then only 1585 bytes. The fluidsynth section is way smaller.

**Comment by mfs12** [comment] 2021-01-19 20:13
Just took your preferences.xml.. but it doesn't make a difference. It's also crashing.

**Comment by mfs12** [comment] 2021-01-19 20:15
This is the output of a crash:

```
(swami:312221): libswami-CRITICAL **: 21:15:33.945: swami_get_control_prop_by_name: assertion 'pspec != NULL' failed

(swami:312221): libswami-CRITICAL **: 21:15:33.945: swami_control_connect_transform: assertion 'SWAMI_IS_CONTROL(src)' failed

(swami:312221): libswami-CRITICAL **: 21:15:33.946: swami_get_control_prop_by_name: assertion 'pspec != NULL' failed

(swami:312221): libswami-CRITICAL **: 21:15:33.946: swami_control_connect_transform: assertion 'SWAMI_IS_CONTROL(src)' failed

(swami:312221): libswami-CRITICAL **: 21:15:33.946: swami_get_control_prop_by_name: assertion 'pspec != NULL' failed

(swami:312221): libswami-CRITICAL **: 21:15:33.946: swami_control_connect_transform: assertion 'SWAMI_IS_CONTROL(src)' failed

(swami:312221): GLib-GObject-WARNING **: 21:15:37.480: g_object_get_is_valid_property: object class 'WavetblFluidSynth' has no property named 'audio.driver-options'
[1]    312221 segmentation fault (core dumped)
```

**Comment by mfs12** [comment] 2021-01-19 20:23
ok, so here's my patch to make function fluid_synth_pref_handler more robust.

```diff
diff --git a/src/plugins/fluidsynth_gui.c b/src/plugins/fluidsynth_gui.c
index 13d3fe1..3079545 100644
--- a/src/plugins/fluidsynth_gui.c
+++ b/src/plugins/fluidsynth_gui.c
@@ -132,9 +132,10 @@ fluid_synth_pref_handler(void)
                                        "text", 0,
                                        NULL);

+        options = NULL;
         g_object_get(swamigui_root->wavetbl, "audio.driver-options", &options, NULL);	/* ++ alloc */

-        for(optionp = options; *optionp; optionp++)
+        for(optionp = options; options && *optionp; optionp++)
         {
             gtk_combo_box_append_text(GTK_COMBO_BOX(widg), *optionp);
         }
@@ -162,9 +163,10 @@ fluid_synth_pref_handler(void)
                                        "text", 0,
                                        NULL);

+        options = NULL;
         g_object_get(swamigui_root->wavetbl, "midi.driver-options", &options, NULL);	/* ++ alloc */

-        for(optionp = options; *optionp; optionp++)
+        for(optionp = options; options && *optionp; optionp++)
         {
             gtk_combo_box_append_text(GTK_COMBO_BOX(widg), *optionp);
         }

```

but this has the downside that the dropdown menus in preferences -> fluidsynth -> driver -> audio driver / midi driver stay empty.

**Comment by jjceresa** [comment] 2021-01-19 20:25
>I did as you told me to, my version of preferences.xml is then only 1585 bytes. The fluidsynth section is way smaller.

This is the indirect cause of the the segmentation fault. I agree that  swami shouldn't crash for this reason. But it seems that recent version of fluidsynth (2.1.6) is may be the cause of the issue. I will look for that.

**Comment by mfs12** [comment] 2021-01-19 20:29
from what i understand you expect swami_wavetbl_get_property should always return a list of properties for audio.driver-options and midi.driver-options. unfortunately this doesn't happen in my case.

Good luck :+1:

**Comment by jjceresa** [comment] 2021-01-19 22:59
@blnagain

>But it seems that recent version of fluidsynth (2.1.6) is perhaps the cause of the issue. I will look for that.
 
Here after using recent fluidsynth version 2.1.6, I cannot reproduce your issue. I mean, after starting swami, opening the preference dialog works without segmentation fault. Also, when quitting swami preferences.xml file is fully written. So, I don't understand what happens on your side.
However, could you confirm the version of `libinstpatch` actually used by swami on your machine ?. This is important because loading/saving xml files is done calling functions inside libinstpatch library.

**Comment by mfs12** [comment] 2021-01-20 07:09
@jjceresa here are all my swami dependencies:
```
Name            : gtk2
Version         : 2.24.33-1
Name            : fftw
Version         : 3.3.9-1
Name            : audiofile
Version         : 0.3.6-6
Name            : fluidsynth
Version         : 2.1.6-1
Name            : libinstpatch
Version         : 1.1.5-1
Name            : libgnomecanvas
Version         : 2.30.3-4
```
I have one last question, how does swami_wavetbl_get_property provide properties for audio.driver-options and midi.driver-options. Because when i looked into the function there was nothing written. Perhaps you could give me a hint and then i have another look on my own. Perhaps i can find a proper solution.

**Comment by mfs12** [comment] 2021-01-20 08:47
I might have found something. A lot of fluidsynth parameters were renamed and have now a dot '.' instead of dash '-' in their names. Which leads to names that are not accepted by the gobject property system. Which then again leads to missing properties when they are accessed i.e. by the preferences dialog.

**Comment by jjceresa** [comment] 2021-01-20 09:30
>how does swami_wavetbl_get_property provide properties for audio.driver-options and midi.driver-options.

Properties comes from fluidsynth settings. When the wavetbl_fluidsynth object is created (in fluidsynth.c) the wavetbl_fluidsynth_class_init() call  fluid_settings_foreach() and the callback settings_foreach_func()  adds each FluidSynth setting as a GObject property.

**Comment by jjceresa** [comment] 2021-01-20 09:35
>Which leads to names that are not accepted by the gobject property system.

I dont think so, because here all is fine and the properties are correctly registered. (using gobject version 2.28.8).

**Comment by jjceresa** [comment] 2021-01-20 09:51
In `settings_foreach_func()`, the `audio driver` setting and `midi driver` settings are `string type` settings with a list of options.
These settings are processed in the `case FLUID_STR_TYPE:` statement by calling `fluid_settings_foreach_option()`.
Finally the property and options are registered at the end of settings_foreach_func() by calling `g_object_class_install_property()`.

**Comment by jjceresa** [comment] 2021-01-20 10:07
>A lot of fluidsynth parameters were renamed and have now a dot '.' instead of dash '-' in their names.

No problem, if you look in wavetbl_fluidsynth_class_init() , there is a the code  to change a dot '.' in '-'. Read comment `have to keep a mapping of property IDs to FluidSynth setting names, since  GObject properties get mangled ('.' turns to '-') `

**Comment by mfs12** [comment] 2021-01-20 10:43
> No problem, if you look in wavetbl_fluidsynth_class_init() , there is a the code to change a dot '.' in '-'. Read comment have to keep a mapping of property IDs to FluidSynth setting names, since GObject properties get mangled ('.' turns to '-') 

You are right and wrong. If you're on master and updated all dependencies, especially libinstpatch to 1.1.6, which is not released officially, then this is true. In version 2.2.1 of swami this patch doesn't exist yet. After patching it locally and rebuilding the following patch fixes the issue. It's kind of a 2.2.1.1 version ;)

Thanks for your help. I think i am going to provide this patch for the Arch Linux package.

```diff
diff --git a/src/plugins/fluidsynth.c b/src/plugins/fluidsynth.c
index 067c6d7..3e7aab9 100644
--- a/src/plugins/fluidsynth.c
+++ b/src/plugins/fluidsynth.c
@@ -752,6 +752,9 @@ settings_foreach_func(void *data, const char *name, int type)
     int optcount = 0;
     char *optname;

+    /* GObject property names don't allow '.' */
+    char *gobj_name = g_strdelimit(g_strdup(name), ".", '-');
+
     /* check if this property is on the string boolean list */
     for(sp = settings_str_bool; *sp; sp++)
         if(type == FLUID_STR_TYPE && strcmp(name, *sp) == 0)
@@ -762,7 +765,7 @@ settings_foreach_func(void *data, const char *name, int type)
     if(*sp)	/* string boolean value? */
     {
         bdef = fluid_settings_str_equal(bag->settings, name, "yes");
-        spec = g_param_spec_boolean(name, name, name, bdef, G_PARAM_READWRITE);
+        spec = g_param_spec_boolean(gobj_name, name, name, bdef, G_PARAM_READWRITE);

         /* set PROP_STRING_BOOL property flag */
         dynamic_prop_flags[last_property_id - FIRST_DYNAMIC_PROP] |= PROP_STRING_BOOL;
@@ -774,7 +777,7 @@ settings_foreach_func(void *data, const char *name, int type)
         case FLUID_NUM_TYPE:
             fluid_settings_getnum_range(bag->settings, name, &dmin, &dmax);
             fluid_settings_getnum_default(bag->settings, name, &ddef);
-            spec = g_param_spec_double(name, name, name, dmin, dmax, ddef,
+            spec = g_param_spec_double(gobj_name, name, name, dmin, dmax, ddef,
                                        G_PARAM_READWRITE);
             break;

@@ -785,18 +788,18 @@ settings_foreach_func(void *data, const char *name, int type)

             if((hint & FLUID_HINT_TOGGLED) != 0)	/* boolean parameter? */
             {
-                spec = g_param_spec_boolean(name, name, name, idef != 0, G_PARAM_READWRITE);
+                spec = g_param_spec_boolean(gobj_name, name, name, idef != 0, G_PARAM_READWRITE);
             }
             else
             {
-                spec = g_param_spec_int(name, name, name, imin, imax, idef, G_PARAM_READWRITE);
+                spec = g_param_spec_int(gobj_name, name, name, imin, imax, idef, G_PARAM_READWRITE);
             }

             break;

         case FLUID_STR_TYPE:
             fluid_settings_getstr_default(bag->settings, name, &defstr);
-            spec = g_param_spec_string(name, name, name, defstr, G_PARAM_READWRITE);
+            spec = g_param_spec_string(gobj_name, name, name, defstr, G_PARAM_READWRITE);

             /* count options for this string parameter (if any) */
             fluid_settings_foreach_option(bag->settings, name, &optcount,
@@ -837,7 +840,7 @@ settings_foreach_func(void *data, const char *name, int type)
     /* install an options parameter if there are any string options */
     if(options)
     {
-        optname = g_strconcat(name, "-options", NULL);	/* ++ alloc */
+        optname = g_strconcat(gobj_name, "-options", NULL);	/* ++ alloc */
         spec = g_param_spec_boxed(optname, optname, optname, G_TYPE_STRV,
                                   G_PARAM_READABLE);

@@ -853,6 +856,8 @@ settings_foreach_func(void *data, const char *name, int type)

         last_property_id++;	/* advance the last dynamic property ID */
     }
+
+    g_free(gobj_name);
 }

 /* function to iterate over FluidSynth string options for string parameters
diff --git a/src/plugins/fluidsynth_gui.c b/src/plugins/fluidsynth_gui.c
index 13d3fe1..a94b281 100644
--- a/src/plugins/fluidsynth_gui.c
+++ b/src/plugins/fluidsynth_gui.c
@@ -132,7 +132,7 @@ fluid_synth_pref_handler(void)
                                        "text", 0,
                                        NULL);

-        g_object_get(swamigui_root->wavetbl, "audio.driver-options", &options, NULL);	/* ++ alloc */
+        g_object_get(swamigui_root->wavetbl, "audio-driver-options", &options, NULL);	/* ++ alloc */

         for(optionp = options; *optionp; optionp++)
         {
@@ -147,7 +147,7 @@ fluid_synth_pref_handler(void)

         /* Connect the audio combo box to the "audio.driver" property */
         swamigui_control_prop_connect_widget(G_OBJECT(swamigui_root->wavetbl),
-                                             "audio.driver", G_OBJECT(widg));
+                                             "audio-driver", G_OBJECT(widg));

         /* Initialize MIDI driver list */
         widg = swamigui_util_glade_lookup(fluid_widg, "ComboMidiDriver");
@@ -162,7 +162,7 @@ fluid_synth_pref_handler(void)
                                        "text", 0,
                                        NULL);

-        g_object_get(swamigui_root->wavetbl, "midi.driver-options", &options, NULL);	/* ++ alloc */
+        g_object_get(swamigui_root->wavetbl, "midi-driver-options", &options, NULL);	/* ++ alloc */

         for(optionp = options; *optionp; optionp++)
         {
```

**Comment by jjceresa** [comment] 2021-01-20 11:17
More hints

>Properties comes from fluidsynth settings. When the wavetbl_fluidsynth object is created (in fluidsynth.c) 

The wavetbl_fluidsynth object is created in swamigui_root_init()  (SwamiguiRoot.c - Line 892)

`    if(type && (root->wavetbl = g_object_new(type, NULL)))`

After that you can try to access to the following "audio-driver" , "midi-driver" properties of root->wavetbl object to verify that these properties exist.

**Comment by jjceresa** [comment] 2021-01-20 11:29
>Thanks for your help. I think i am going to provide this patch for the Arch Linux package

Ok, if this fix the issue for you, please feel free to do a PR here. 
And please what is the gobject version you are using ?

**Comment by mfs12** [comment] 2021-01-20 11:39
> And please what is the gobject version you are using ?

As gobject is part of glib2... my glib2 version is 2.66.4.

**Comment by mfs12** [comment] 2021-01-20 11:43
Ok, i have a branch ready... but it doesn't make sense to merge it into master, as master already has this fix.

Would make sense to create 2.2.x branch or something so you can easily make a simple bug fix release.

**Comment by jjceresa** [comment] 2021-01-20 12:02
>Ok, i have a branch ready... but it doesn't make sense to merge it into master, as master already has this fix.

No, master as not yet this fix. I am currently doing the PR on a new branch that I will call `prop-name`.

**Comment by jjceresa** [comment] 2021-01-20 12:29
>my glib2 version is 2.66.4.

So here is the difference, gobject 2.66.4 doesn't accept dot character '.' in property name. But gobject version 2.28.8 replace dot '.' by '-'.  Many thanks for reporting this bug.

**Comment by jjceresa** [comment] 2021-01-20 13:10
>No, master as not yet this fix.

I just realize that this fix already exist on github master but not on my local master but as I am using gobject 2.28.8 this issue never occur.

**Comment by mfs12** [comment] 2021-01-20 13:52
> I just realize that this fix already exist on github master but not on my local master but as I am using gobject 2.28.8 this issue never occur.
 
Told you... ;)

**Comment by mfs12** [comment] 2021-01-20 13:57
But i got another issue... after working everything through for 2.2.1 i realized that the properties

- audio-output-channels and
- audio-input-channels

are missing. So i get a crash again because those properties are use in swami-2.ui. Can you confirm those values still exist?

**Comment by jjceresa** [comment] 2021-01-20 15:20
Looking in https://www.fluidsynth.org/api/settings_audio.html , I don't see any settings for `audio-output-channels` and `audio-input-channels`. In swami-2.ui these values look like an old leftover pertinent to FluidSynth-Audio:jack.
I am not a jack user, @derselbst could you confirm that those settings are still valid ?

**Comment by mfs12** [comment] 2021-01-20 23:05
@jjceresa here are my fixes for 2.2.1. the last 2 commits might be interesting for your master. they remove obsolete ui elements and fix some chorus property validation.

https://github.com/blnagain/swami/tree/fix-property-get-crash

**Comment by jjceresa** [comment] 2021-01-21 12:50
>the last 2 commits might be interesting for your master. they remove obsolete ui elements and fix some chorus property validation.

Yes`, the last 2 commits seems interesting, thanks:
- `fluidsynth: fixed validation of chorus count, freq and depth`
- `swami: removed obsolete ui elements in jack's preference section

Commit:  `fluidsynth: fixed more names of properties` is partially incorrect.
- changes in fluidsynth_gui.c seems correct because here we are talking about true gobject's property name (i.e without dot '.').
- changes in fluidsynth.c on names in `settings_str_bool[]` seems not correct and should be reverted. The name here are fluidsynth settings names, and fluidsynth doesn't rely on gobject. You can notice that `settings_str_bool[]` is used in the context of fluid_settings_foreach() fluidsynth API which expect valid fluidsynth settings name as for example https://www.fluidsynth.org/api/fluidsettings.xml#synth.chorus.active or  https://www.fluidsynth.org/api/fluidsettings.xml#synth.cpu-cores. 

I think it worth you push PRs here.

**Comment by mfs12** [comment] 2021-01-21 14:19
> changes in fluidsynth.c on names in `settings_str_bool[]` seems not correct and should be reverted. The name here are fluidsynth settings names, and fluidsynth doesn't rely on gobject. You can notice that `settings_str_bool[]` is used in the context of fluid_settings_foreach() fluidsynth API which expect valid fluidsynth settings name as for example https://www.fluidsynth.org/api/fluidsettings.xml#synth.chorus.active or  https://www.fluidsynth.org/api/fluidsettings.xml#synth.cpu-cores.

i fixed that in my branch. thanks.

**Comment by jjceresa** [comment] 2021-01-21 14:42
Also, chorus depth max shouldn't be > 46, because fluidsynth internal limit is lower than the max setting. If we set 256 this will reduce the effective range of the graphic depth button. Make a try by moving the button and you will get fluisynth messages on the console.

`    g_object_class_install_property(obj_class, WTBL_PROP_CHORUS_DEPTH,
                                    g_param_spec_double("chorus-depth", _("Chorus depth"),
                                            _("Chorus depth"),
                                            0.0, 46.0, chorus_presets[0].depth,

**Comment by mfs12** [comment] 2021-01-21 17:56
Hey, you are absolutely right... although documentation of fluidsynth says something different. https://www.fluidsynth.org/api/settings_synth.html...

Changed it to 46. Thanks.

**Comment by derselbst** [comment] 2021-01-21 18:48
Ok, I now understand that this is the same issue than the one already fixed by #59. I should have made a new release earlier. I forgot about that. Sorry. I'll try to catch up with everything on the weekend.

I can confirm that `audio-output-channels` and `audio-input-channels` are no fluidsynth settings. I don't know where they come from.

I don't quite understand what's about the upper limit of the `synth.chorus.depth` setting. Is fluidsynth's upper limit of 256 right or wrong?

**Comment by mfs12** [comment] 2021-01-21 19:13
> I don't quite understand what's about the upper limit of the synth.chorus.depth setting. Is fluidsynth's upper limit of 256 right or wrong?

At least this is what the documentation says. But It also throws a warning when you exceed a value of about 46. So the knob wouldn't be as handy.

```
wavetbl_fluidsynth_set_property(1094)chorus.depth 43,885714
wavetbl_fluidsynth_set_property(1094)chorus.depth 46,080000
fluidsynth: warning: chorus: Too high depth. Setting it to max (2048).
```

**Comment by jjceresa** [comment] 2021-01-21 19:45
>Is fluidsynth's upper limit of 256 right or wrong?

It is right. 256 ms is the maximum value obtained using a sample rate min (8000Hz) for  a delay line of fixed length of 2048 samples.

However, for swami FluidSynth gui, this doesn't  mean that we should set  256 for the maximum value of the depth button. For a default sample rate of 44100Hz we should set `max` depth button to 46 ms ( (2048 * 1000)/ sample_rate) to not exceed the internal fixed chorus delay size.

**Comment by derselbst** [comment] 2021-01-22 20:37
Thanks for explaining, JJC. I've cherry-picked the two relevant commits. I will probably make a release by tomorrow.

**Comment by jjceresa** [comment] 2021-01-25 12:28
>I will probably make a release by tomorrow.

Please, could you wait before a release.

>However, for swami FluidSynth gui, this doesn't mean that we should set 256 for the maximum value of the depth button. For a default sample rate of 44100Hz we should set max depth button to 46 ms

As swami accepts sample rate change (via the preference dialog), we must set `max depth property` based on the `maximum sample rate ` accepted by fluidsynth: max depth button = ((2048 * 1000)/ max_sample_rate) = ((2048 * 1000)/ 96000 = 20

I will do a PR today.

**Closed as completed** 2021-01-25 13:16 UTC
Labels: bug
